export const FETCH_ALL_POSTS_REQUEST = "FETCH_ALL_POSTS_REQUEST";
export const FETCH_ALL_POSTS_SUCCESS = "FETCH_ALL_POSTS_SUCCESS";
export const FETCH_ALL_POSTS_FAILURE = "FETCH_ALL_POSTS_FAILURE";

export const FETCH_USER_POSTS_REQUEST = "FETCH_USER_POSTS_REQUEST";
export const FETCH_USER_POSTS_SUCCESS = "FETCH_USER_POSTS_SUCCESS";
export const FETCH_USER_POSTS_FAILURE = "FETCH_USER_POSTS_FAILURE";

export const LIKE_REQUEST = "LIKE_REQUEST";
export const LIKE_SUCCESS = "LIKE_SUCCESS";
export const LIKE_FAILURE = "LIKE_FAILURE";

export const POST_COMMENT_SUCCESS = "POST_COMMENT_SUCCESS";
export const POST_COMMENT_REQUEST = "POST_COMMENT_REQUEST";
export const POST_COMMENT_FAIL = "POST_COMMENT_FAIL";

export const UPDATE_COMMENT_SUCCESS = "UPDATE_COMMENT_SUCCESS";
export const UPDATE_COMMENT_REQUEST = "UPDATE_COMMENT_REQUEST";
export const UPDATE_COMMENT_FAIL = "UPDATE_COMMENT_FAIL";

export const FETCH_MY_POSTS_REQUEST = "FETCH_MY_POSTS_REQUEST";
export const FETCH_MY_POSTS_SUCCESS = "FETCH_MY_POSTS_SUCCESS";
export const FETCH_MY_POSTS_FAILURE = "FETCH_MY_POSTS_FAILURE";

export const CREATE_MY_POSTS_REQUEST = "CREATE_MY_POSTS_REQUEST";
export const CREATE_MY_POSTS_SUCCESS = "CREATE_MY_POSTS_SUCCESS";
export const CREATE_MY_POSTS_FAILURE = "CREATE_MY_POSTS_FAILURE";
export const CREATE_MY_POSTS_RESET = "CREATE_MY_POSTS_RESET";

export const UPDATE_MY_POSTS_REQUEST = "UPDATE_MY_POSTS_REQUEST";
export const UPDATE_MY_POSTS_SUCCESS = "UPDATE_MY_POSTS_SUCCESS";
export const UPDATE_MY_POSTS_FAILURE = "UPDATE_MY_POSTS_FAILURE";
export const UPDATE_MY_POSTS_RESET = "UPDATE_MY_POSTS_RESET";

export const DELETE_MY_POSTS_REQUEST = "DELETE_MY_POSTS_REQUEST";
export const DELETE_MY_POSTS_SUCCESS = "DELETE_MY_POSTS_SUCCESS";
export const DELETE_MY_POSTS_FAILURE = "DELETE_MY_POSTS_FAILURE";
export const DELETE_MY_POSTS_RESET = "DELETE_MY_POSTS_RESET";

export const ADMIN_POSTS_REQUEST = "ADMIN_POSTS_REQUEST";
export const ADMIN_POSTS_SUCCESS = "ADMIN_POSTS_SUCCESS";
export const ADMIN_POSTS_FAILURE = "ADMIN_POSTS_FAILURE";

export const CREATE_MY_STORY_REQUEST = "CREATE_MY_STORY_REQUEST";
export const CREATE_MY_STORY_SUCCESS = "CREATE_MY_STORY_SUCCESS";
export const CREATE_MY_STORY_FAILURE = "CREATE_MY_STORY_FAILURE";
export const CREATE_MY_STORY_RESET = "CREATE_MY_STORY_RESET";

export const FETCH_ALL_STORY_REQUEST = "FETCH_ALL_STORY_REQUEST";
export const FETCH_ALL_STORY_SUCCESS = "FETCH_ALL_STORY_SUCCESS";
export const FETCH_ALL_STORY_FAILURE = "FETCH_ALL_STORY_FAILURE";

export const CLEAR_ERRORS = "CLEAR_ERRORS";
export const CLEAR_MESSAGE = "CLEAR_MESSAGE";
